# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'Astray' do
    
    pod 'Firebase', '>= 2.5.0'
    pod 'GeoFire', '>= 1.1'

end

target 'AstrayTests' do

    pod 'Firebase', '>= 2.5.0'
    pod 'GeoFire', '>= 1.1'

end

target 'AstrayUITests' do

    pod 'Firebase', '>= 2.5.0'
    pod 'GeoFire', '>= 1.1'

end

